#!/bin/bash

bold="$(tput bold)"
tput0="$(tput sgr0)"
red="$(tput setaf 1)"
blue="$(tput setaf 4)"

heldc="$blue"
unheldc="$red"

#pattern="beta"

. /usr/local/bin/editscript

#while getopts ":p:e" opt; do
#  case ${opt} in
#    p )
#      pattern="$OPTARG"
#      ;;
#    e )
#      editscript
#      exit 0
#      ;;
#    help|h )
#      echo "Invalid option: -$OPTARG" >&2
#      exit 1
#      ;;
#    : )
#      echo "Option -$OPTARG requires an argument." >&2
#      exit 1
#      ;;
#  esac
#done

is_held() {
    for held in "${heldpkgs[@]}"; do
        if [[ "$held" == "$1" ]]; then
            return 0
        fi
    done
    return 1
}


while (( $# > 0 )); do
  if [[ "$1" = "-p" || "$1" = "--pattern" ]]; then
    pattern="$2"
    shift 2
  elif [[ "$1" = "-s" || "$1" = "--skip" ]]; then
    skipup=true
    shift
  elif [[ "$1" = "-e" || "$1" = "--edit" ]]; then
    editscript
    exit 0
  elif [[ "$1" = "-v" ]]; then
    verbose=true
    shift
  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
    printf 'Usage: %s [-p <pattern>] [-e] [-h] [-s] [-v]\n' "${0##*/}"
    printf '  -p <pattern>    Specify the package pattern (default: "beta")\n'
    printf '  -e              Edit the script\n'
    echo "  -s              Skip apt update"
    echo "  -v              Verbose output"
    echo "  -h              Show this help message"
    exit 0
  else
    echo "Invalid option: $1"
    exit 1
  fi
done

! "${skipup:=false}" && printf 'Updating package lists...\n' && sudo apt update

if [[ "$pattern" ]]; then
  #pkgmatch=$(apt list --upgradable 2>/dev/null | grep -i "$pattern")
  readarray -t pkgmatch < <(apt list --upgradeable 2>/dev/null|\grep -i "$pattern")
  IFS=; pkgmatchsplat="${pkgmatch[*]}"; unset IFS
  if (( ${#pkgmatch[@]} > 0 )) && [[ "${pkgmatchsplat[*]}" ]]; then
	 echo "Listing upgradeable packages matching pattern '$pattern'..."
     echo "The following packages matching '$pattern' are upgradeable:"
     for i in "${pkgmatch[@]}"; do #while IFS= read -r package; do
       pkgname="${package%%\/*}"
       if is_held "$pkgname"; then
         echo -e "${heldc}${pkgname}${tput0} (held)"
       else
         echo -e "${unheldc}${pkgname}${tput0} (unheld)"
       fi
     done
     echo "${heldc}on ice    ${tput0}—    ${unheldc}concern${tput0}"
     pause "Press Enter to continue..."
  else
    echo "No packages matching '$pattern' found."
#    exit 0
  fi

  for pkgname in "${pkgmatch[@]}"; do
    pkgname="${pkgname%%\/*}"
    while true; do

      if is_held "$pkgname"; then
        package_color="$heldc"
      else
        package_color="$unheldc"
      fi

      echo -e "${bold}\nOptions for package '${package_color}${pkgname}${tput0}':${tput0}"
      "${verbose:=false}" && apt list "$pkgname" -a
      if is_held "$pkgname"; then
          echo "1) ${unheldc}Release hold${tput0}"
      else
          echo "1) ${heldc}Mark as hold${tput0}"
      fi
      echo "2) Show package details"
      echo "${bold}3) Skip to next package${tput0} [default]"
      echo "4) Quit"

      read -rp "Choose an option: " choice < /dev/tty
      choice=${choice:-3}

      case $choice in
        1)
          if is_held "$pkgname"; then
            sudo apt-mark unhold "$pkgname"
            echo "$pkgname has been released from hold."
          else
            sudo apt-mark hold "$pkgname"
            echo "$pkgname has been marked as hold."
          fi
          break
          ;;
        2)
          apt show "$pkgname"
          apt list "$pkgname" -a
          pause "Press Enter to return to the options..."
          ;;
        3)
          break
          ;;
        4)
          echo "Quitting..."
          exit 0
          ;;
        *)
          echo "Invalid option. Please choose 1, 2, 3, or 4."
          ;;
      esac
    done
  done

  echo "All packages matching '$pattern' processed."

fi


printf '\nGetting list of currently held packages...\n'
readarray -t heldpkgs < <(apt-mark showhold)
#if (( "${#heldpkgs[@]}" > 0 ))
for i in "${heldpkgs[@]}"; do printf \ \ %s%s%s%s\\n "$bold" "$heldc" "$i" "$tput0"; done
printf \\n
! "${skipup:=false}" && pause Press\ any\ key\ to\ continue...
printf \\n

if (( ${#heldpkgs[@]} > 0 )); then
#  echo "The following packages are currently held:"
  for heldpkg in "${heldpkgs[@]}"; do
#    printf %s%s%s%s\\n "$bold" "$heldc" "$heldpkg" "$tput0"
    while true; do
      "${verbose:=false}" && printf 'Information from apt list for %s%s%s%s:\n\n' "$heldc" "$bold" "$heldpkg" "$tput0" && apt list -a "$heldpkg"
      printf '%sOptions for held package %s%s%s:\n\n' "$bold" "$heldc" "$heldpkg" "$tput0"
      printf '1) %s%sRelease hold%s\n' "${bold}" "${unheldc}" "${tput0}"
      printf '%s2) Skip to next package%s [default]\n' "$bold" "$tput0"
      printf '3) Show details for %s%s%s%s\n' "$bold" "$heldc" "$heldpkg" "$tput0"
      printf '4) Quit\n'

      read -rp "Choose an option: " choice < /dev/tty
      choice=${choice:-2}

      case $choice in
        1)
          sudo apt-mark unhold "$heldpkg"
          echo "$heldpkg has been released from hold."
          break
          ;;
        2)
          printf '\n%s%s%s%s is held\n' "$bold" "$heldc" "$heldpkg" "$tput0"
          break
          ;;
        3)
          printf '\napt list -a "$heldpkg":\n' "$heldpkg"
          apt list -a "$heldpkg"
          ;;
        4)
          echo "Quitting..."
          exit 0
          ;;
        *)
          echo "Invalid option. Please choose 1, 2, 3, or 4."
          ;;
      esac
    done
  done
#  pause "Press Enter to continue..."
else
  echo "No packages are currently held."
fi

printf \\n
